### ISSUE TITLE
"TypeError: paLib is not a constructor" - Problem with AC2729/10

### ISSUE THREAD

**Issue by chucky2002** [bvmensvoort/node-red-contrib-philips-air#2]
It does not work with Phillips AC2729/10. In Red-Node I get "TypeError: paLib is not a constructor" .
I attached the flow.json 

[flows(1).zip](https://github.com/bvmensvoort/node-red-contrib-philips-air/files/5234583/flows.1.zip)

**Comment by bvmensvoort** [comment]
Thanks for mentioning this. It seems to be an issue for the CoAP and PlainCoAP usage.
