### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by unclej84** [bvmensvoort/node-red-contrib-philips-air#7]
Hi,

just wanted to check if you could update the npm package in the Repository so that Node-Red can fetch the updated version? Somehow the github actions did not do it.

Thanks in advance.

**Comment by bvmensvoort** [comment]
Thanks for mentioning this.
It seems that the github action for publishing to npm doesn't work. I will look at this when there will be a new release for the plugin.
In the meanwhile, I manually updated the npmjs registry and Node-RED registry. So, it should be able to automatically upgrade in Node-RED now.
